baseURL = 'https://aikatssukamen.github.io/blog'
languageCode = 'ja-jp'
title = '記録'
theme = 'diary'

[outputs]
  home = ['HTML', 'JSON']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
